openapi: 3.1.0
info:
  title: 
    Fn::Sub: ${AWS::StackName}-api # API Gatewayに生成されるAPI名
  version: '1.0'
paths:
  /slideshow/upload:
    post:
      summary: 'Upload Photo For SlideShow'
      consumes:
        - multipart/form-data
      parameters:
        - description: 'Photo Data to be uploaded'
          in: formData
          name: file
          required: true
          type: file
      responses:
        200:
          description: 'Success'
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SlideShowUploadFunction.Arn}/invocations
        passthroughBehavior: when_no_templates
        httpMethod: POST
        type: aws_proxy
