AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  server
  
  Sample SAM Template for server

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    Runtime: go1.x
    Architectures:
      - x86_64      

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prd
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: api/api.yaml
  SlideShowUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/slideshow
      Handler: handler
